/* UTF-8 data patch for archive and character pages */

charactersData.length = 0;
charactersData.push(
  {
    id: "chen-shuisheng",
    name: "陈水生",
    title: "玩家化身 · 运河少年",
    role: "情感代入",
    historicalLabel: "虚构人物",
    recordType: "虚构人物",
    faction: "运河支队互动叙事",
    chapters: "序章、杜庄、护送线、炸桥行动、战后选择",
    accent: "#6a8a4a",
    fallbackBg: "linear-gradient(135deg, #6a8a4a 0%, #2a2a18 100%)",
    fallbackText: "水生",
    chop: "主角",
    backChop: "生",
    avatar: "./assets/characters/stills/chen-shuisheng.jpg",
    memoryLine: "从失去家园的孩子，成长为守护运河的人。",
    bio: "运河边长大的少年，作为玩家进入历史的化身。他的经历承接了加入支队、初战胆怯、秘密护送与胜利前夜等关键体验。",
    relationship: "他就是玩家的视角。玩家的每一次选择，都会改变他如何理解勇气、纪律与守护。",
    storyLine: "标注：陈水生为虚构人物，用来承载互动叙事与玩家成长线。",
    quote: "运河不能丢，家也不能丢。",
    hidden: false,
    unlocked: true
  },
  {
    id: "sun-bolong",
    name: "孙伯龙",
    title: "运河支队支队长",
    role: "建队与作战指挥",
    historicalLabel: "真实人物",
    recordType: "史实人物",
    faction: "运河支队",
    chapters: "周营集结、初战杜庄",
    accent: "#8b1a1a",
    fallbackBg: "linear-gradient(135deg, #8b1a1a 0%, #3d0808 100%)",
    fallbackText: "伯龙",
    chop: "帅",
    backChop: "龙",
    avatar: "./assets/characters/stills/sun-bolong.jpg",
    memoryLine: "把分散的抗日力量拧成一股绳。",
    bio: "1940 年周营镇建队后，孙伯龙作为支队长带领队伍在运河两岸坚持敌后抗战。人物库中突出他的凝聚力、指挥力和敢打能打的气质。",
    relationship: "在陈水生眼里，孙伯龙第一次让他明白：害怕不是错，退后才会让家园失守。",
    storyLine: "史实为基底，游戏中对具体战斗场景进行视角化呈现。",
    quote: "守住阵地，就是守住两岸百姓的命脉。",
    hidden: false,
    unlocked: true
  },
  {
    id: "zhu-daonan",
    name: "朱道南",
    title: "运河支队政委",
    role: "信念与群众工作",
    historicalLabel: "真实人物",
    recordType: "史实人物",
    faction: "运河支队",
    chapters: "周营集结、队伍建设",
    accent: "#d4943a",
    fallbackBg: "linear-gradient(135deg, #8b6914 0%, #4a3008 100%)",
    fallbackText: "道南",
    chop: "政",
    backChop: "南",
    avatar: "./assets/characters/stills/zhao-zhengwei.jpg",
    memoryLine: "让队伍不仅会打仗，也知道为什么而战。",
    bio: "朱道南在人物库中承担信念维度：政治动员、组织建设与群众工作，让运河支队与两岸百姓形成共同抗战的力量。",
    relationship: "他影响陈水生理解支队为何而战，帮助少年把个人仇恨转化为守护家乡的责任。",
    storyLine: "史实人物。游戏中会将组织工作压缩为更适合互动体验的场景与台词。",
    quote: "队伍有了方向，枪口才有分量。",
    hidden: false,
    unlocked: true
  },
  {
    id: "shao-jianqiu",
    name: "邵剑秋",
    title: "运河支队副支队长",
    role: "秘密交通线与护送",
    historicalLabel: "真实人物",
    recordType: "史实人物",
    faction: "运河支队",
    chapters: "寒夜护送、北许阳、德胜庄夜渡",
    accent: "#5a7a8a",
    fallbackBg: "linear-gradient(135deg, #5a7a8a 0%, #1e3a4a 100%)",
    fallbackText: "剑秋",
    chop: "护",
    backChop: "秋",
    avatar: "./assets/characters/stills/shao-jianqiu.jpg",
    memoryLine: "寒夜任务里的沉稳护送者。",
    bio: "在秘密护送线中，他代表保密、判断与责任。页面中将他呈现为夜渡任务的组织者，提醒玩家越重要的任务越要沉住气。",
    relationship: "他让陈水生学会：战斗不只有冲锋，也包括守口如瓶、辨认路线、护住队伍。",
    storyLine: "史实为基底，游戏对护送过程进行了节点化、选择化改编。",
    quote: "越重要的任务，越要把声音压低，把心放稳。",
    hidden: false,
    unlocked: true
  },
  {
    id: "hu-daxun",
    name: "胡大勋",
    title: "运河支队参谋长",
    role: "战场导师",
    historicalLabel: "真实人物",
    recordType: "史实人物",
    faction: "运河支队",
    chapters: "序章招募、杜庄战后",
    accent: "#6b6b6b",
    fallbackBg: "linear-gradient(135deg, #7a7a7a 0%, #3a3a3a 100%)",
    fallbackText: "大勋",
    chop: "勋",
    backChop: "勋",
    avatar: "./assets/characters/stills/hu-daxun.jpg",
    memoryLine: "一句“运河儿女就要保运河”，把少年拉进历史。",
    bio: "负责招募、训练与作战安排。游戏中他既是把陈水生带进队伍的人，也是战后提醒他重新站起来的导师。",
    relationship: "他在陈水生犹豫、害怕时给出最直接的提醒：想留下，就得学会不怕。",
    storyLine: "史实人物与游戏导师功能结合，部分台词为剧情化表达。",
    quote: "运河儿女，就要保运河。",
    hidden: false,
    unlocked: true
  },
  {
    id: "chen-yi",
    name: "陈毅",
    title: "新四军军长 · 代号张处长",
    role: "秘密护送对象",
    historicalLabel: "真实人物",
    recordType: "史实人物",
    faction: "新四军",
    chapters: "寒夜护送",
    accent: "#b8933a",
    fallbackBg: "linear-gradient(135deg, #8b6914 0%, #5a3e08 100%)",
    fallbackText: "陈毅",
    chop: "军",
    backChop: "毅",
    avatar: "./assets/characters/stills/chen-yi.jpg",
    memoryLine: "乔装过运河，奔赴延安。",
    bio: "1943 年，陈毅乔装为“张处长”，经运河沿线秘密交通线继续前往延安。人物库中先强调代号与保密，再揭示真实身份。",
    relationship: "他不是主角光环，而是让陈水生看见：一条秘密路线背后，可能牵动整个抗战大局。",
    storyLine: "史实为基底，游戏突出秘密交通线的危险与保密压力。",
    quote: "年轻娃子守家门，好样的。",
    hidden: false,
    unlocked: true
  },
  {
    id: "tong-qiulong",
    name: "童邱龙",
    title: "护送线关联人物",
    role: "秘密路线协同",
    historicalLabel: "真实人物",
    recordType: "关联人物",
    faction: "护送行动",
    chapters: "寒夜护送、杜安集、德胜庄",
    accent: "#8a6f3a",
    fallbackBg: "linear-gradient(135deg, #8a6f3a 0%, #2a2416 100%)",
    fallbackText: "邱龙",
    chop: "线",
    backChop: "邱",
    avatar: "./assets/characters/stills/lao-ban-zhang.jpg",
    memoryLine: "一句“别说话，快着走”，把夜路压得更紧。",
    bio: "作为护送线扩展人物出现，承担路线提醒、队伍压速、临近据点时的警戒氛围。",
    relationship: "他让陈水生感到，秘密任务中每一步都不能出声，每一次停顿都可能暴露。",
    storyLine: "关联人物小卡，用于补足护送档案旁的行动网络。",
    quote: "别说话，快着走。",
    hidden: false,
    unlocked: true
  },
  {
    id: "zhu-xiaochun",
    name: "朱孝春",
    title: "爆破行动成员",
    role: "韩庄桥爆破",
    historicalLabel: "真实人物 / 行动人物",
    recordType: "行动人物",
    faction: "爆破组",
    chapters: "韩庄大桥行动",
    accent: "#8b6914",
    fallbackBg: "linear-gradient(135deg, #8b6914 0%, #4a3008 100%)",
    fallbackText: "孝春",
    chop: "破",
    backChop: "春",
    avatar: "./assets/characters/stills/zhu-xiaochun.jpg",
    memoryLine: "把炸药送到桥下的人。",
    bio: "绑定炸桥行动的关键人物，突出爆破任务的危险、速度和临场判断。游戏中他带领玩家穿过火力网。",
    relationship: "如果玩家选择爆破队，朱孝春就是带着陈水生贴近桥洞的人。",
    storyLine: "行动记录会与韩庄大桥档案联动呈现。",
    quote: "再近一点，胜利就近一点。",
    hidden: false,
    unlocked: true
  },
  {
    id: "hu-dalun",
    name: "胡大伦",
    title: "排长 / 行动指挥语境",
    role: "阻击与爆破协同",
    historicalLabel: "剧情化人物 / 行动原型",
    recordType: "剧情化改编",
    faction: "桥头行动组",
    chapters: "韩庄大桥行动",
    accent: "#c4631e",
    fallbackBg: "linear-gradient(135deg, #c4631e 0%, #6b2a08 100%)",
    fallbackText: "大伦",
    chop: "令",
    backChop: "伦",
    avatar: "./assets/characters/stills/hu-dalun.jpg",
    memoryLine: "把爆破与阻击拧成一次行动。",
    bio: "适合与朱孝春一起组成爆破行动成员组，承担任务分配、阻击掩护与行动节奏。",
    relationship: "他给陈水生最后一次战斗选择：去爆破，还是去掩护。",
    storyLine: "为增强游戏叙事，将行动指挥语境集中到人物卡中呈现。",
    quote: "桥要断，敌人的路也要断。",
    hidden: false,
    unlocked: true
  }
);

timelineData.length = 0;
timelineData.push(
  {
    id: "beacon-fire",
    time: "1938",
    title: "烽火运河：徐州会战后的敌后抗战",
    tag: "背景",
    mapLocation: "徐州、津浦线、运河两岸",
    routeIndex: "01",
    coordinate: "津浦线被切断",
    oneLiner: "为什么运河重要？因为城镇与交通线被敌人控制后，运河两岸成为敌后坚持抗战的重要通道。",
    historicalFacts: "1938 年徐州会战后，日军控制主要城镇和交通线，国民党主力向西南方向转移。中国共产党领导的敌后武装在运河两岸等区域坚持抗日斗争。",
    gameAdaptation: "游戏把这一背景压缩为开场史料层：黑白地图、被切断的交通线与玩家即将进入的运河地带。",
    playerEcho: "少年手记：我第一次知道，家门口这条河不只是河，它也是队伍能不能走下去的路。",
    archiveForm: "黑白地图 / 红色交通线标记 / 小问答",
    unlockCondition: "进入首页即可查看"
  },
  {
    id: "zhouying-assembly",
    time: "1940.01.01",
    title: "周营集结：运河支队成立",
    tag: "建队",
    mapLocation: "周营镇",
    routeIndex: "02",
    coordinate: "周营镇集结点",
    oneLiner: "一支约 1500 人的抗日武装，在周营镇正式打出运河支队的番号。",
    historicalFacts: "1940 年 1 月 1 日，运河支队在周营镇正式成立，孙伯龙任支队长，朱道南任政委，邵剑秋任副支队长，胡大勋任参谋长，队伍约 1500 人。",
    gameAdaptation: "玩家在序章中以陈水生的身份选择是否加入支队。不同选项对应复仇、牵挂家人或求生等动机。",
    playerEcho: "解锁条件：完成序章“加入运河支队”。\n档案标记：新兵入列。",
    archiveForm: "成立令 / 队伍合影式插画 / 人物关系图",
    unlockCondition: "完成序章“加入运河支队”后解锁"
  },
  {
    id: "first-battle-duzhuang",
    time: "1940",
    title: "初战杜庄：从害怕到担当",
    tag: "首战",
    mapLocation: "杜庄村",
    routeIndex: "03",
    coordinate: "杜庄村口阵地",
    oneLiner: "这不是一份战果清单，而是少年第一次学会面对枪声的档案。",
    historicalFacts: "运河支队成立后，需要在实战中积累战斗经验、守住阵地、保护群众，并在敌后环境中逐渐形成作战能力。",
    gameAdaptation: "脚本以杜庄战斗为核心，让玩家在守正面、转移村民、临阵退缩之间选择，突出害怕之后如何站起来。",
    playerEcho: "你选择守正面：档案标记为“正面阻击”。\n你选择转移村民：档案标记为“护民行动”。\n你选择退缩：档案标记为“未完成的勇气”。",
    archiveForm: "战斗简报 / 三个选择分支记录 / 战后手记",
    unlockCondition: "完成第一章杜庄战斗后解锁"
  },
  {
    id: "cold-night-escort",
    time: "1943.12",
    title: "寒夜护送：秘密交通线与陈毅过运河",
    tag: "绝密",
    mapLocation: "北许阳、杜安集、德胜庄",
    routeIndex: "04",
    coordinate: "夜渡德胜庄",
    oneLiner: "此任务不得声张：一位“张处长”的身份，关系着一条秘密交通线。",
    historicalFacts: "1943 年 12 月，陈毅乔装为“张处长”，在运河支队等护送下，经北许阳、杜安集、德胜庄附近涉水过运河，继续前往延安。",
    gameAdaptation: "游戏把护送线做成保密档案：先显示“张处长”，完成护送后揭示陈毅身份，并加入放哨、认人、夜渡等选择。",
    playerEcho: "少年手记：陈军长的手很暖。我想，一定要守住这个秘密，不能让他出事。",
    archiveForm: "秘密路线图 / 伪装身份卡 / 夜渡场景 / 口令式交互",
    unlockCondition: "完成第二章护送任务后解锁"
  },
  {
    id: "bridge-demolition",
    time: "1945.10.28",
    title: "炸桥行动：韩庄大桥与胜利前夜",
    tag: "爆破",
    mapLocation: "韩庄运河铁路桥、公路桥",
    routeIndex: "05",
    coordinate: "韩庄大桥",
    oneLiner: "炸桥不是为了破坏，而是为了让更多通向未来的桥重新立起来。",
    historicalFacts: "1945 年 10 月 28 日前后，部队破袭津浦铁路柳泉至韩庄段，炸毁韩庄运河铁路大桥、公路大桥，以阻止国民党军沿铁路北犯，并迫使日伪军彻底投降。",
    gameAdaptation: "第三章让玩家选择加入爆破队、阻击组或退缩。朱孝春与胡大伦的行动记录绑定在这一档案中。",
    playerEcho: "你选择爆破队：档案标记为“桥下爆破”。\n你选择阻击组：档案标记为“桥头掩护”。\n你选择退缩：档案标记为“可耻的逃兵”。",
    archiveForm: "爆破任务图 / 桥梁结构剖面 / 行动成员记录",
    unlockCondition: "完成第三章韩庄桥行动后解锁"
  }
);
